version: 2
jobs:
  golang:latest:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go test ./...
      - run: go vet ./...
  coveralls:
    docker:
      - image: circleci/golang:latest
    steps:
      - run: go install github.com/mattn/goveralls
      - checkout
      - run: go test -v -cover -race -coverprofile=coverage.out ./...
      - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - golang:latest
      - coveralls
